DROP TABLE IF EXISTS SALE;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS USER;


CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  stock VARCHAR(250) NOT NULL,
  price VARCHAR(250) DEFAULT NULL,
  status VARCHAR(250) DEFAULT NULL
);

CREATE TABLE SALE (
  id_sale INT AUTO_INCREMENT  PRIMARY KEY,
  identification VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  mail VARCHAR(250) DEFAULT NULL,
  phone VARCHAR(250) DEFAULT NULL,
  id INT REFERENCES PRODUCT(id)
);


CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  lastname VARCHAR(250) NOT NULL,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  perfil VARCHAR(250) DEFAULT NULL,
  status VARCHAR(250) DEFAULT NULL
);

INSERT INTO USER (name, lastname, username, password, perfil, status) VALUES
  ('Alex', 'Merino', 'alex','abc123', 'ADMIN','1'),
  ('User', 'Test', 'test','abc123', 'USER','1');